/**
 *	@author Ariana Fairbanks
 */

package adapter;

public enum ViewStates 
{
	LOGIN, SETTINGS, PASSWORDCHANGE, VIEWGAMERECORDS, VIEWSTUDENTSTATS,
	ROOTMENU, ADDUSERS, MANAGEDATA,
	TEACHERMENU, SELECTSTUDENTRECORDS,
	STUDENTMENU, GAME1, GAME2, GAME3
}